name: Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install homeassistant
      - name: Run Hassfest
        uses: home-assistant/actions/hassfest@master
      - name: Check Home Assistant version
        run: |
          python -c "import homeassistant; print(homeassistant.__version__)"
      - name: Validate manifest
        run: |
          python -c "import json; json.load(open('custom_components/mwan3/manifest.json'))"
      - name: Validate translations
        run: |
          python -c "import json; json.load(open('custom_components/mwan3/translations/en.json'))" 